{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "67b212a3-4100-4589-98d5-50f6e08af8de",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:5000\n",
      "Press CTRL+C to quit\n",
      "127.0.0.1 - - [05/Jan/2026 01:17:54] \"GET / HTTP/1.1\" 302 -\n",
      "127.0.0.1 - - [05/Jan/2026 01:17:54] \"GET /login HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [05/Jan/2026 01:17:57] \"GET /register HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [05/Jan/2026 01:18:04] \"POST /register HTTP/1.1\" 302 -\n",
      "127.0.0.1 - - [05/Jan/2026 01:18:04] \"GET /login HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [05/Jan/2026 01:18:18] \"POST /login HTTP/1.1\" 302 -\n",
      "127.0.0.1 - - [05/Jan/2026 01:18:18] \"GET /dashboard HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, render_template_string, request, redirect, url_for, session, flash\n",
    "import sqlite3\n",
    "import time \n",
    "from datetime import datetime, timedelta\n",
    "import secrets\n",
    "import hashlib\n",
    "import os\n",
    "from functools import wraps\n",
    "import smtplib\n",
    "from email.mime.text import MIMEText\n",
    "from email.mime.multipart import MIMEMultipart\n",
    "import threading\n",
    "from IPython.display import display, HTML\n",
    "\n",
    "app = Flask(__name__)\n",
    "app.secret_key = secrets.token_hex(32)\n",
    "app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(hours=24)\n",
    "\n",
    "government_code = {\n",
    "    '01': 'Cairo', '02': 'Alexandria',\n",
    "    '03': 'Port Said', '04': 'Suez',\n",
    "    '11': 'Damietta', '12': 'Dakahlia',\n",
    "    '13': 'Ash Sharqia', '14': 'Kaliobeya',\n",
    "    '15': 'Kafr El-Sheikh', '16': 'Gharbia',\n",
    "    '17': 'Menoufia', '18': 'Beheira',\n",
    "    '19': 'Ismailia', '21': 'Giza', \n",
    "    '22': 'Beni Suef', '23': 'Fayoum',\n",
    "    '24': 'Minya', '25': 'Assiut',\n",
    "    '26': 'Sohag', '27': 'Qena',\n",
    "    '28': 'Aswan', '29': 'Luxor',\n",
    "    '31': 'Red Sea', '32': 'New Valley',\n",
    "    '33': 'Matrouh', '34': 'North Sinai',\n",
    "    '35': 'South Sinai', '88': 'Foreign'\n",
    "}\n",
    "\n",
    "class EgyptNationalID::\n",
    "    def __init__(self,national_id):\n",
    "        self.national_id = national_id\n",
    "        self.birth_date  = None\n",
    "        self.government  = None\n",
    "        self.gender      = None\n",
    "        self.user_age    = None\n",
    "        self.valid       = self.validiate_national_id()\n",
    "    \n",
    "    def validiate_national_id(self):\n",
    "        if len(self.national_id) !=14 or not self.national_id.isdigit():\n",
    "            return False\n",
    "        \n",
    "        year=self.national_id[0]\n",
    "        year_number=self.national_id[1:3]\n",
    "        month = self.national_id[3:5]\n",
    "        day = self.national_id[5:7]\n",
    "        government_id = self.national_id[7:9]\n",
    "        rest_of_id = self.national_id[9:13]\n",
    "            \n",
    "        if(year==\"2\"):\n",
    "            full_year = \"19\" + year_number\n",
    "        elif(year==\"3\"):\n",
    "            full_year = \"20\" + year_number\n",
    "        else:\n",
    "            return False    \n",
    "        \n",
    "        if(int(rest_of_id) % 2==1):\n",
    "            self.gender = \"male\" \n",
    "        else:\n",
    "            self.gender =  \"female\"\n",
    "        \n",
    "        try:\n",
    "            self.birth_date = datetime.strptime(f\"{full_year}{month}{day}\", \"%Y%m%d\")\n",
    "            self.birth_date_str = self.birth_date.strftime(\"%Y-%m-%d\")\n",
    "        except ValueError:\n",
    "            return False\n",
    "        \n",
    "        # government_code should be defined somewhere\n",
    "        self.government = government_code.get(government_id, 'Unknown')\n",
    "        \n",
    "        # Calculate age\n",
    "        today = datetime.now().date()\n",
    "        birth = self.birth_date.date()\n",
    "        self.user_age = today.year - birth.year - ((today.month, today.day) < (birth.month, birth.day))\n",
    "        \n",
    "        return True        \n",
    "\n",
    "class EmailConfig:\n",
    "    SENDER_EMAIL = os.getenv(\"EMAIL_ADDRESS\", \"your_email@gmail.com\")\n",
    "    SENDER_PASSWORD = os.getenv(\"EMAIL_PASSWORD\", \"your_app_password\")\n",
    "    SMTP_SERVER = \"smtp.gmail.com\"\n",
    "    SMTP_PORT = 587\n",
    "\n",
    "class EmailService:\n",
    "    @staticmethod\n",
    "    def send_verification_code(to_email, code, name):\n",
    "        try:\n",
    "            message = MIMEMultipart('alternative')\n",
    "            message['From'] = EmailConfig.SENDER_EMAIL\n",
    "            message['To'] = to_email\n",
    "            message['Subject'] = f\"Verification Code - {name}\"\n",
    "            html_body = f\"\"\"\n",
    "            <html><body style=\"font-family: Arial; text-align: center; background: #f4f4f4; padding: 20px;\">\n",
    "            <div style=\"background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px; border-radius: 20px;\">\n",
    "            <div style=\"background: white; max-width: 500px; margin: auto; padding: 40px; border-radius: 15px;\">\n",
    "            <h1 style=\"color: #667eea;\">Hello {name}!</h1>\n",
    "            <p style=\"color: #666; font-size: 16px;\">Thank you for registering</p>\n",
    "            <hr style=\"border: none; border-top: 2px solid #f0f0f0; margin: 20px 0;\">\n",
    "            <p style=\"color: #666; font-size: 18px;\">Use this code to verify your account:</p>\n",
    "            <div style=\"background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; border-radius: 10px; margin: 20px 0;\">\n",
    "            <p style=\"color: white; font-size: 48px; font-weight: bold; letter-spacing: 8px; margin: 0;\">{code}</p>\n",
    "            </div>\n",
    "            <div style=\"background: #fff3cd; border: 2px solid #ffc107; border-radius: 8px; padding: 12px; margin: 20px 0;\">\n",
    "            <p style=\"color: #856404; font-size: 14px; margin: 0;\">Code valid for 15 minutes</p>\n",
    "            </div></div></div></body></html>\n",
    "            \"\"\"\n",
    "            message.attach(MIMEText(html_body, 'html'))\n",
    "            with smtplib.SMTP(EmailConfig.SMTP_SERVER, EmailConfig.SMTP_PORT) as server:\n",
    "                server.starttls()\n",
    "                server.login(EmailConfig.SENDER_EMAIL, EmailConfig.SENDER_PASSWORD)\n",
    "                server.send_message(message)\n",
    "            return True\n",
    "        except Exception as e:\n",
    "            print(f\"Email error: {e}\")\n",
    "            return False\n",
    "\n",
    "class DatabaseManager:\n",
    "    def __init__(self):\n",
    "        self.conn = sqlite3.connect('fuckn_complete_system.db',\n",
    "                                     check_same_thread=False,\n",
    "                                     timeout=10)\n",
    "        self.conn.execute('PRAGMA journal_mode=WAL;')\n",
    "        self.create_tables()\n",
    "    \n",
    "    def create_tables(self):\n",
    "        c = self.conn.cursor()\n",
    "        #pending user\n",
    "        c.execute(\"\"\"CREATE TABLE IF NOT EXISTS pending_users (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            national_id TEXT UNIQUE NOT NULL CHECK(length(national_id) = 14),\n",
    "            birth_date TEXT,\n",
    "            government TEXT,\n",
    "            gender TEXT,\n",
    "            age    INTEGER,\n",
    "            first_name TEXT NOT NULL,\n",
    "            last_name TEXT NOT NULL,\n",
    "            email TEXT NOT NULL UNIQUE,\n",
    "            password_hash TEXT NOT NULL,\n",
    "            code_hash TEXT NOT NULL,\n",
    "            created_at TEXT NOT NULL,\n",
    "            expires_at TEXT NOT NULL,\n",
    "            attempts INTEGER DEFAULT 0)\"\"\")\n",
    "        #main user\n",
    "        c.execute(\"\"\"CREATE TABLE IF NOT EXISTS users (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            national_id TEXT UNIQUE NOT NULL CHECK(length(national_id) = 14),\n",
    "            birth_date TEXT,\n",
    "            government TEXT,\n",
    "            gender TEXT,\n",
    "            age    INTEGER,\n",
    "            first_name TEXT NOT NULL,\n",
    "            last_name TEXT NOT NULL,\n",
    "            email TEXT NOT NULL UNIQUE,\n",
    "            password_hash TEXT NOT NULL,\n",
    "            verified BOOLEAN DEFAULT 1,\n",
    "            created_at TEXT NOT NULL, last_login TEXT)\"\"\")\n",
    "        #session \n",
    "        c.execute(\"\"\"CREATE TABLE IF NOT EXISTS sessions (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            user_id INTEGER NOT NULL,\n",
    "            session_token TEXT UNIQUE NOT NULL,\n",
    "            created_at TEXT NOT NULL,\n",
    "            expires_at TEXT NOT NULL,\n",
    "            FOREIGN KEY (user_id) REFERENCES users(id))\"\"\")\n",
    "        self.conn.commit()\n",
    "\n",
    "db = DatabaseManager()\n",
    "\n",
    "def get_db():\n",
    "    return db.conn\n",
    "\n",
    "def login_required(f):\n",
    "    @wraps(f)\n",
    "    def decorated_function(*args, **kwargs):\n",
    "        if 'user_id' not in session:\n",
    "            flash('Please login first', 'warning')\n",
    "            return redirect(url_for('login'))\n",
    "        return f(*args, **kwargs)\n",
    "    return decorated_function\n",
    "\n",
    "CSS = \"\"\"<style>\n",
    "* { margin: 0; padding: 0; box-sizing: border-box; }\n",
    "body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; display: flex; justify-content: center; align-items: center; padding: 20px; }\n",
    ".container { background: white; border-radius: 20px; box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3); padding: 40px; max-width: 500px; width: 100%; animation: slideIn 0.5s ease; }\n",
    "@keyframes slideIn { from { opacity: 0; transform: translateY(-20px); } to { opacity: 1; transform: translateY(0); } }\n",
    ".dashboard-container { max-width: 900px; }\n",
    "h1 { color: #667eea; margin-bottom: 10px; text-align: center; font-size: 28px; }\n",
    "h2 { color: #667eea; margin-bottom: 30px; text-align: center; font-size: 24px; }\n",
    ".form-group { margin-bottom: 20px; }\n",
    "label { display: block; color: #333; font-weight: 600; margin-bottom: 8px; font-size: 14px; }\n",
    "input[type=\"text\"], input[type=\"email\"], input[type=\"password\"] { width: 100%; padding: 12px 15px; border: 2px solid #e0e0e0; border-radius: 8px; font-size: 16px; transition: border-color 0.3s; }\n",
    "input:focus { outline: none; border-color: #667eea; }\n",
    ".btn { width: 100%; padding: 14px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border: none; border-radius: 8px; font-size: 18px; font-weight: bold; cursor: pointer; transition: transform 0.2s, box-shadow 0.2s; margin-top: 10px; }\n",
    ".btn:hover { transform: translateY(-2px); box-shadow: 0 10px 25px rgba(102, 126, 234, 0.4); }\n",
    ".btn-secondary { background: linear-gradient(135deg, #6c757d 0%, #495057 100%); }\n",
    ".btn-secondary:hover { box-shadow: 0 10px 25px rgba(108, 117, 125, 0.4); }\n",
    ".links { text-align: center; margin-top: 20px; color: #666; font-size: 14px; }\n",
    ".links a { color: #667eea; text-decoration: none; font-weight: 600; }\n",
    ".links a:hover { text-decoration: underline; }\n",
    ".alert { padding: 12px 20px; border-radius: 8px; margin-bottom: 20px; font-weight: 500; animation: fadeIn 0.3s ease; }\n",
    "@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }\n",
    ".alert-success { background-color: #d4edda; color: #155724; border: 1px solid #c3e6cb; }\n",
    ".alert-error { background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }\n",
    ".alert-warning { background-color: #fff3cd; color: #856404; border: 1px solid #ffc107; }\n",
    ".user-card { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 40px; border-radius: 15px; margin-bottom: 30px; text-align: center; box-shadow: 0 10px 30px rgba(102, 126, 234, 0.4); }\n",
    ".user-card h3 { font-size: 36px; margin-bottom: 10px; font-weight: bold; }\n",
    ".user-card .email { font-size: 18px; opacity: 0.9; }\n",
    ".info-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-bottom: 30px; }\n",
    ".info-item { background: #f8f9fa; padding: 25px; border-radius: 12px; border-left: 5px solid #667eea; transition: transform 0.2s, box-shadow 0.2s; }\n",
    ".info-item:hover { transform: translateY(-5px); box-shadow: 0 5px 20px rgba(0, 0, 0, 0.1); }\n",
    ".info-label { color: #666; font-size: 12px; font-weight: 600; text-transform: uppercase; margin-bottom: 10px; letter-spacing: 1px; }\n",
    ".info-value { color: #333; font-size: 20px; font-weight: bold; }\n",
    ".verify-code { background: #fff3cd; border: 2px solid #ffc107; padding: 20px; border-radius: 10px; text-align: center; margin-bottom: 25px; }\n",
    ".verify-code p { color: #856404; font-weight: 600; margin: 5px 0; }\n",
    ".verify-code strong { color: #664d03; }\n",
    "input[type=\"text\"].code-input { text-align: center; font-size: 32px; letter-spacing: 12px; font-weight: bold; font-family: 'Courier New', monospace; }\n",
    "</style>\"\"\"\n",
    "\n",
    "LOGIN_TEMPLATE = CSS + \"\"\"\n",
    "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Login</title></head><body>\n",
    "<div class=\"container\"><h1>🇪🇬 Egyptian Authentication</h1><h2>🔐 Login</h2>\n",
    "{% with messages = get_flashed_messages(with_categories=true) %}{% if messages %}{% for category, message in messages %}<div class=\"alert alert-{{ category }}\">{{ message }}</div>{% endfor %}{% endif %}{% endwith %}\n",
    "<form method=\"POST\" action=\"{{ url_for('login') }}\">\n",
    "<div class=\"form-group\"><label for=\"email\">📧 Email Address</label><input type=\"email\" id=\"email\" name=\"email\" required placeholder=\"your.email@example.com\"></div>\n",
    "<div class=\"form-group\"><label for=\"password\">🔒 Password</label><input type=\"password\" id=\"password\" name=\"password\" required placeholder=\"Enter your password\"></div>\n",
    "<button type=\"submit\" class=\"btn\">🔓 Login to Dashboard</button></form>\n",
    "<div class=\"links\">Don't have an account? <a href=\"{{ url_for('register') }}\">Register here</a></div></div></body></html>\n",
    "\"\"\"\n",
    "\n",
    "REGISTER_TEMPLATE = CSS + \"\"\"\n",
    "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Register</title></head><body>\n",
    "<div class=\"container\"><h1>🇪🇬 Egyptian Authentication</h1><h2>📝 Register New Account</h2>\n",
    "{% with messages = get_flashed_messages(with_categories=true) %}{% if messages %}{% for category, message in messages %}<div class=\"alert alert-{{ category }}\">{{ message }}</div>{% endfor %}{% endif %}{% endwith %}\n",
    "<form method=\"POST\" action=\"{{ url_for('register') }}\">\n",
    "<div class=\"form-group\"><label for=\"national_id\">🆔 National ID (14 digits)</label><input type=\"text\" id=\"national_id\" name=\"national_id\" pattern=\"[0-9]{14}\" maxlength=\"14\" required placeholder=\"29901011234567\"><small style=\"color: #666; font-size: 12px;\">Example: 29901011234567</small></div>\n",
    "<div class=\"form-group\"><label for=\"first_name\">👤 First Name</label><input type=\"text\" id=\"first_name\" name=\"first_name\" required placeholder=\"Ahmed\"></div>\n",
    "<div class=\"form-group\"><label for=\"last_name\">👤 Last Name</label><input type=\"text\" id=\"last_name\" name=\"last_name\" required placeholder=\"Mohamed\"></div>\n",
    "<div class=\"form-group\"><label for=\"email\">📧 Email Address</label><input type=\"email\" id=\"email\" name=\"email\" required placeholder=\"your.email@example.com\"></div>\n",
    "<div class=\"form-group\"><label for=\"password\">🔒 Password</label><input type=\"password\" id=\"password\" name=\"password\" required placeholder=\"Create a strong password\"></div>\n",
    "<button type=\"submit\" class=\"btn\">📧 Send Verification Code</button></form>\n",
    "<div class=\"links\">Already have an account? <a href=\"{{ url_for('login') }}\">Login here</a></div></div></body></html>\n",
    "\"\"\"\n",
    "\n",
    "VERIFY_TEMPLATE = CSS + \"\"\"\n",
    "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Verify</title></head><body>\n",
    "<div class=\"container\"><h1>🇪🇬 Egyptian Authentication</h1><h2>✅ Verify Your Account</h2>\n",
    "<div class=\"verify-code\"><p>📧 Check your email: <strong>{{ email }}</strong></p><p>⏰ Code valid for <strong>15 minutes</strong></p><p>🔢 Maximum <strong>3 attempts</strong></p></div>\n",
    "{% with messages = get_flashed_messages(with_categories=true) %}{% if messages %}{% for category, message in messages %}<div class=\"alert alert-{{ category }}\">{{ message }}</div>{% endfor %}{% endif %}{% endwith %}\n",
    "<form method=\"POST\" action=\"{{ url_for('verify') }}\">\n",
    "<div class=\"form-group\"><label for=\"code\">🔢 Enter 6-Digit Verification Code</label><input type=\"text\" id=\"code\" name=\"code\" class=\"code-input\" pattern=\"[0-9]{6}\" maxlength=\"6\" required placeholder=\"123456\" autocomplete=\"off\"></div>\n",
    "<button type=\"submit\" class=\"btn\">✅ Verify & Access Dashboard</button></form>\n",
    "<div class=\"links\">Wrong email? <a href=\"{{ url_for('register') }}\">Register again</a></div></div>\n",
    "<script>document.getElementById('code').focus();</script></body></html>\n",
    "\"\"\"\n",
    "\n",
    "DASHBOARD_TEMPLATE = CSS + \"\"\"\n",
    "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Dashboard</title></head><body>\n",
    "<div class=\"container dashboard-container\"><h1>🇪🇬 User Dashboard</h1>\n",
    "{% with messages = get_flashed_messages(with_categories=true) %}{% if messages %}{% for category, message in messages %}<div class=\"alert alert-{{ category }}\">{{ message }}</div>{% endfor %}{% endif %}{% endwith %}\n",
    "<div class=\"user-card\"><h3>👤 {{ user.first_name }} {{ user.last_name }}</h3><p class=\"email\">📧 {{ user.email }}</p></div>\n",
    "<div class=\"info-grid\">\n",
    "<div class=\"info-item\"><div class=\"info-label\">🆔 National ID</div><div class=\"info-value\">{{ user.national_id }}</div></div>\n",
    "<div class=\"info-item\"><div class=\"info-label\">🎂 Date of Birth</div><div class=\"info-value\">{{ user.birth_date }}</div></div>\n",
    "<div class=\"info-item\"><div class=\"info-label\">📍 Government</div><div class=\"info-value\">{{ user.government }}</div></div>\n",
    "<div class=\"info-item\"><div class=\"info-label\">⚧️ Gender</div><div class=\"info-value\">{{ user.gender }}</div></div>\n",
    "<div class=\"info-item\"><div class=\"info-label\"> age</div><div class=\"info-value\">{{ user.age }}</div></div>\n",
    "<div class=\"info-item\"><div class=\"info-label\">📅 Member Since</div><div class=\"info-value\">{{ user.created_at[:10] }}</div></div>\n",
    "<div class=\"info-item\"><div class=\"info-label\">🕐 Last Login</div><div class=\"info-value\">{{ user.last_login[:10] if user.last_login else 'First Login' }}</div></div>\n",
    "</div>\n",
    "<a href=\"{{ url_for('logout') }}\" style=\"text-decoration: none;\"><button class=\"btn btn-secondary\">🚪 Logout</button></a>\n",
    "</div></body></html>\n",
    "\"\"\"\n",
    "\n",
    "@app.route('/')\n",
    "def index():\n",
    "    if 'user_id' in session:\n",
    "        return redirect(url_for('dashboard'))\n",
    "    return redirect(url_for('login'))\n",
    "\n",
    "@app.route('/register', methods=['GET', 'POST'])\n",
    "def register():\n",
    "    if request.method == 'POST':\n",
    "        national_id = request.form.get('national_id', '').strip()\n",
    "        first_name = request.form.get('first_name', '').strip()\n",
    "        last_name = request.form.get('last_name', '').strip()\n",
    "        email = request.form.get('email', '').strip()\n",
    "        password = request.form.get('password', '').strip()\n",
    "        if not all([national_id, first_name, last_name, email, password]):\n",
    "            flash('All fields are required', 'error')\n",
    "            return redirect(url_for('register'))\n",
    "        egypt_id = EgyptNationalID(national_id)\n",
    "        if not egypt_id.valid:\n",
    "            flash('Invalid Egyptian National ID', 'error')\n",
    "            return redirect(url_for('register'))\n",
    "        conn = get_db()\n",
    "        c = conn.execute(\"SELECT email FROM users WHERE email = ?\", (email,))\n",
    "        if c.fetchone():\n",
    "            flash('Email already registered. Please login.', 'error')\n",
    "            return redirect(url_for('login'))\n",
    "        code = ''.join([str(secrets.randbelow(10)) for _ in range(6)])\n",
    "        password_hash = hashlib.sha256(password.encode()).hexdigest()\n",
    "        code_hash = hashlib.sha256(code.encode()).hexdigest()\n",
    "        created_at = datetime.now().isoformat()\n",
    "        expires_at = (datetime.now() + timedelta(minutes=15)).isoformat()\n",
    "        try:\n",
    "            conn.execute('DELETE FROM pending_users WHERE email = ?', (email,))\n",
    "            conn.execute('''INSERT INTO pending_users (national_id, birth_date, government, gender, age, email, first_name, last_name, password_hash, code_hash, created_at, expires_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)''', (national_id, egypt_id.birth_date_str, egypt_id.government, egypt_id.gender, egypt_id.age, email, first_name, last_name, password_hash, code_hash, created_at, expires_at))\n",
    "            conn.commit()\n",
    "            if EmailService.send_verification_code(email, code, first_name):\n",
    "                session['pending_email'] = email\n",
    "                flash(f'Verification code sent to {email}! Check your inbox.', 'success')\n",
    "                return redirect(url_for('verify'))\n",
    "            else:\n",
    "                flash('Failed to send verification email.', 'error')\n",
    "                return redirect(url_for('register'))\n",
    "        except Exception as e:\n",
    "            flash(f'Registration failed: {str(e)}', 'error')\n",
    "            return redirect(url_for('register'))\n",
    "    return render_template_string(REGISTER_TEMPLATE)\n",
    "\n",
    "@app.route('/verify', methods=['GET', 'POST'])\n",
    "def verify():\n",
    "    if 'pending_email' not in session:\n",
    "        flash('Please register first', 'warning')\n",
    "        return redirect(url_for('register'))\n",
    "    if request.method == 'POST':\n",
    "        email = session.get('pending_email')\n",
    "        code = request.form.get('code', '').strip()\n",
    "        if not code:\n",
    "            flash('Please enter verification code', 'error')\n",
    "            return redirect(url_for('verify'))\n",
    "        code_hash = hashlib.sha256(code.encode()).hexdigest()\n",
    "        conn = get_db()\n",
    "        c = conn.execute(\"\"\"SELECT national_id, birth_date, government, gender, age, first_name, last_name, password_hash, expires_at, attempts FROM pending_users WHERE email = ? AND code_hash = ?\"\"\", (email, code_hash))\n",
    "        result = c.fetchone()\n",
    "        if not result:\n",
    "            conn.execute('UPDATE pending_users SET attempts = attempts + 1 WHERE email = ?', (email,))\n",
    "            conn.commit()\n",
    "            c = conn.execute('SELECT attempts FROM pending_users WHERE email = ?', (email,))\n",
    "            attempts_result = c.fetchone()\n",
    "            if attempts_result and attempts_result[0] >= 3:\n",
    "                conn.execute('DELETE FROM pending_users WHERE email = ?', (email,))\n",
    "                conn.commit()\n",
    "                session.pop('pending_email', None)\n",
    "                flash('Maximum attempts exceeded. Please register again.', 'error')\n",
    "                return redirect(url_for('register'))\n",
    "            remaining = 3 - (attempts_result[0] if attempts_result else 0)\n",
    "            flash(f'Wrong code! Attempts remaining: {remaining}', 'error')\n",
    "            return redirect(url_for('verify'))\n",
    "        national_id, birth_date, government, gender, age, first_name, last_name, password_hash, expires_at, attempts = result\n",
    "        if datetime.now() > datetime.fromisoformat(expires_at):\n",
    "            conn.execute('DELETE FROM pending_users WHERE email = ?', (email,))\n",
    "            conn.commit()\n",
    "            session.pop('pending_email', None)\n",
    "            flash('Verification code expired. Please register again.', 'error')\n",
    "            return redirect(url_for('register'))\n",
    "        try:\n",
    "            created_at = datetime.now().isoformat()\n",
    "            c = conn.execute('''INSERT INTO users (national_id, birth_date, government, gender, age, email, first_name, last_name, password_hash, created_at) \n",
    "                                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)''', \n",
    "                             (national_id, birth_date, government, gender, age, email, first_name, last_name, password_hash, created_at))\n",
    "            user_id = c.lastrowid\n",
    "            conn.commit()\n",
    "            conn.execute('DELETE FROM pending_users WHERE email = ?', (email,))\n",
    "            conn.commit()\n",
    "            session.pop('pending_email', None)\n",
    "            session['user_id'] = user_id\n",
    "            session['email'] = email\n",
    "            session['first_name'] = first_name\n",
    "            session['last_name'] = last_name\n",
    "            session.permanent = True\n",
    "            flash(f'Account verified successfully! Welcome {first_name}!', 'success')\n",
    "            return redirect(url_for('dashboard'))\n",
    "        except Exception as e:\n",
    "            flash(f'Verification failed: {str(e)}', 'error')\n",
    "            return redirect(url_for('verify'))\n",
    "    return render_template_string(VERIFY_TEMPLATE, email=session.get('pending_email'))\n",
    "\n",
    "@app.route('/login', methods=['GET', 'POST'])\n",
    "def login():\n",
    "    if request.method == 'POST':\n",
    "        email = request.form.get('email', '').strip()\n",
    "        password = request.form.get('password', '').strip()\n",
    "        if not email or not password:\n",
    "            flash('Email and password are required', 'error')\n",
    "            return redirect(url_for('login'))\n",
    "        password_hash = hashlib.sha256(password.encode()).hexdigest()\n",
    "        conn = get_db()\n",
    "        c = conn.execute(\"\"\"SELECT id, first_name, last_name, national_id, birth_date, government,  gender, age FROM users WHERE email = ? AND password_hash = ?\"\"\", (email, password_hash))\n",
    "        result = c.fetchone()\n",
    "        if result:\n",
    "            user_id, first_name, last_name, national_id, birth_date, government, gender, age = result\n",
    "            session['user_id'] = user_id\n",
    "            session['email'] = email\n",
    "            session['first_name'] = first_name\n",
    "            session['last_name'] = last_name\n",
    "            session['national_id'] = national_id\n",
    "            session['birth_date'] = birth_date\n",
    "            session['government'] = government\n",
    "            session['gender'] = gender\n",
    "            session['age'] = age\n",
    "            session.permanent = True\n",
    "            last_login = datetime.now().isoformat()\n",
    "            conn.execute('UPDATE users SET last_login = ? WHERE id = ?', (last_login, user_id))\n",
    "            conn.commit()\n",
    "            flash(f'Welcome back, {first_name}!', 'success')\n",
    "            return redirect(url_for('dashboard'))\n",
    "        else:\n",
    "            flash('Invalid email or password', 'error')\n",
    "            return redirect(url_for('login'))\n",
    "    return render_template_string(LOGIN_TEMPLATE)\n",
    "\n",
    "@app.route('/dashboard')\n",
    "@login_required\n",
    "def dashboard():\n",
    "    conn = get_db()\n",
    "    c = conn.execute(\"\"\"SELECT first_name, last_name, email, national_id, birth_date, government, gender, age, created_at, last_login FROM users WHERE id = ?\"\"\", (session['user_id'],))\n",
    "    user = c.fetchone()\n",
    "    if user:\n",
    "        user_data = {\n",
    "            'first_name': user[0], \n",
    "            'last_name': user[1], 'email': user[2], 'national_id': user[3], 'birth_date': user[4], 'government': user[5], 'gender': user[6], 'age': user[7], 'created_at': user[8], 'last_login': user[9]}\n",
    "        return render_template_string(DASHBOARD_TEMPLATE, user=user_data)\n",
    "    else:\n",
    "        flash('User not found', 'error')\n",
    "        return redirect(url_for('login'))\n",
    "\n",
    "@app.route('/logout')\n",
    "def logout():\n",
    "    name = session.get('first_name', 'User')\n",
    "    session.clear()\n",
    "    flash(f'Goodbye {name}! Logged out successfully.', 'success')\n",
    "    return redirect(url_for('login'))\n",
    "\n",
    "# Function to run Flask in a separate thread for Jupyter\n",
    "def run_flask():\n",
    "    app.run(debug=False, host='127.0.0.1', port=5000, use_reloader=False)\n",
    "\n",
    "# Start Flask server in background thread\n",
    "flask_thread = threading.Thread(target=run_flask, daemon=True)\n",
    "flask_thread.start()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e5b3d57a-18fe-4775-8e2a-0cdb691ef007",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:5000\n",
      "Press CTRL+C to quit\n",
      "Exception in thread Thread-37:\n",
      "Traceback (most recent call last):\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\urllib3\\connection.py\"\u001b[0m, line \u001b[35m198\u001b[0m, in \u001b[35m_new_conn\u001b[0m\n",
      "    sock = connection.create_connection(\n",
      "        (self._dns_host, self.port),\n",
      "    ...<2 lines>...\n",
      "        socket_options=self.socket_options,\n",
      "    )\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\urllib3\\util\\connection.py\"\u001b[0m, line \u001b[35m85\u001b[0m, in \u001b[35mcreate_connection\u001b[0m\n",
      "    raise err\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\urllib3\\util\\connection.py\"\u001b[0m, line \u001b[35m73\u001b[0m, in \u001b[35mcreate_connection\u001b[0m\n",
      "    \u001b[31msock.connect\u001b[0m\u001b[1;31m(sa)\u001b[0m\n",
      "    \u001b[31m~~~~~~~~~~~~\u001b[0m\u001b[1;31m^^^^\u001b[0m\n",
      "\u001b[1;35mConnectionRefusedError\u001b[0m: \u001b[35m[WinError 10061] No connection could be made because the target machine actively refused it\u001b[0m\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\urllib3\\connectionpool.py\"\u001b[0m, line \u001b[35m787\u001b[0m, in \u001b[35murlopen\u001b[0m\n",
      "    response = self._make_request(\n",
      "        conn,\n",
      "    ...<10 lines>...\n",
      "        **response_kw,\n",
      "    )\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\urllib3\\connectionpool.py\"\u001b[0m, line \u001b[35m493\u001b[0m, in \u001b[35m_make_request\u001b[0m\n",
      "    \u001b[31mconn.request\u001b[0m\u001b[1;31m(\u001b[0m\n",
      "    \u001b[31m~~~~~~~~~~~~\u001b[0m\u001b[1;31m^\u001b[0m\n",
      "        \u001b[1;31mmethod,\u001b[0m\n",
      "        \u001b[1;31m^^^^^^^\u001b[0m\n",
      "    ...<6 lines>...\n",
      "        \u001b[1;31menforce_content_length=enforce_content_length,\u001b[0m\n",
      "        \u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u001b[0m\n",
      "    \u001b[1;31m)\u001b[0m\n",
      "    \u001b[1;31m^\u001b[0m\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\urllib3\\connection.py\"\u001b[0m, line \u001b[35m494\u001b[0m, in \u001b[35mrequest\u001b[0m\n",
      "    \u001b[31mself.endheaders\u001b[0m\u001b[1;31m()\u001b[0m\n",
      "    \u001b[31m~~~~~~~~~~~~~~~\u001b[0m\u001b[1;31m^^\u001b[0m\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\http\\client.py\"\u001b[0m, line \u001b[35m1333\u001b[0m, in \u001b[35mendheaders\u001b[0m\n",
      "    \u001b[31mself._send_output\u001b[0m\u001b[1;31m(message_body, encode_chunked=encode_chunked)\u001b[0m\n",
      "    \u001b[31m~~~~~~~~~~~~~~~~~\u001b[0m\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u001b[0m\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\http\\client.py\"\u001b[0m, line \u001b[35m1093\u001b[0m, in \u001b[35m_send_output\u001b[0m\n",
      "    \u001b[31mself.send\u001b[0m\u001b[1;31m(msg)\u001b[0m\n",
      "    \u001b[31m~~~~~~~~~\u001b[0m\u001b[1;31m^^^^^\u001b[0m\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\http\\client.py\"\u001b[0m, line \u001b[35m1037\u001b[0m, in \u001b[35msend\u001b[0m\n",
      "    \u001b[31mself.connect\u001b[0m\u001b[1;31m()\u001b[0m\n",
      "    \u001b[31m~~~~~~~~~~~~\u001b[0m\u001b[1;31m^^\u001b[0m\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\urllib3\\connection.py\"\u001b[0m, line \u001b[35m325\u001b[0m, in \u001b[35mconnect\u001b[0m\n",
      "    self.sock = \u001b[31mself._new_conn\u001b[0m\u001b[1;31m()\u001b[0m\n",
      "                \u001b[31m~~~~~~~~~~~~~~\u001b[0m\u001b[1;31m^^\u001b[0m\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\urllib3\\connection.py\"\u001b[0m, line \u001b[35m213\u001b[0m, in \u001b[35m_new_conn\u001b[0m\n",
      "    raise NewConnectionError(\n",
      "        self, f\"Failed to establish a new connection: {e}\"\n",
      "    ) from e\n",
      "\u001b[1;35murllib3.exceptions.NewConnectionError\u001b[0m: \u001b[35m<urllib3.connection.HTTPConnection object at 0x00000113F59E9810>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\u001b[0m\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\adapters.py\"\u001b[0m, line \u001b[35m667\u001b[0m, in \u001b[35msend\u001b[0m\n",
      "    resp = conn.urlopen(\n",
      "        method=request.method,\n",
      "    ...<9 lines>...\n",
      "        chunked=chunked,\n",
      "    )\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\urllib3\\connectionpool.py\"\u001b[0m, line \u001b[35m841\u001b[0m, in \u001b[35murlopen\u001b[0m\n",
      "    retries = retries.increment(\n",
      "        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "    )\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\urllib3\\util\\retry.py\"\u001b[0m, line \u001b[35m519\u001b[0m, in \u001b[35mincrement\u001b[0m\n",
      "    \u001b[1;31mraise MaxRetryError(_pool, url, reason) from reason\u001b[0m  # type: ignore[arg-type]\n",
      "    \u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u001b[0m\n",
      "\u001b[1;35murllib3.exceptions.MaxRetryError\u001b[0m: \u001b[35mHTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000113F59E9810>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\u001b[0m\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\threading.py\"\u001b[0m, line \u001b[35m1043\u001b[0m, in \u001b[35m_bootstrap_inner\u001b[0m\n",
      "    \u001b[31mself.run\u001b[0m\u001b[1;31m()\u001b[0m\n",
      "    \u001b[31m~~~~~~~~\u001b[0m\u001b[1;31m^^\u001b[0m\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\threading.py\"\u001b[0m, line \u001b[35m1344\u001b[0m, in \u001b[35mrun\u001b[0m\n",
      "    \u001b[31mself.function\u001b[0m\u001b[1;31m(*self.args, **self.kwargs)\u001b[0m\n",
      "    \u001b[31m~~~~~~~~~~~~~\u001b[0m\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^^\u001b[0m\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\flask_ngrok.py\"\u001b[0m, line \u001b[35m70\u001b[0m, in \u001b[35mstart_ngrok\u001b[0m\n",
      "    ngrok_address = _run_ngrok()\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\flask_ngrok.py\"\u001b[0m, line \u001b[35m35\u001b[0m, in \u001b[35m_run_ngrok\u001b[0m\n",
      "    tunnel_url = \u001b[31mrequests.get\u001b[0m\u001b[1;31m(localhost_url)\u001b[0m.text  # Get the tunnel information\n",
      "                 \u001b[31m~~~~~~~~~~~~\u001b[0m\u001b[1;31m^^^^^^^^^^^^^^^\u001b[0m\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\"\u001b[0m, line \u001b[35m73\u001b[0m, in \u001b[35mget\u001b[0m\n",
      "    return request(\"get\", url, params=params, **kwargs)\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\"\u001b[0m, line \u001b[35m59\u001b[0m, in \u001b[35mrequest\u001b[0m\n",
      "    return \u001b[31msession.request\u001b[0m\u001b[1;31m(method=method, url=url, **kwargs)\u001b[0m\n",
      "           \u001b[31m~~~~~~~~~~~~~~~\u001b[0m\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u001b[0m\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\"\u001b[0m, line \u001b[35m589\u001b[0m, in \u001b[35mrequest\u001b[0m\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\"\u001b[0m, line \u001b[35m703\u001b[0m, in \u001b[35msend\u001b[0m\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \u001b[35m\"C:\\Users\\HiTecH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\adapters.py\"\u001b[0m, line \u001b[35m700\u001b[0m, in \u001b[35msend\u001b[0m\n",
      "    raise ConnectionError(e, request=request)\n",
      "\u001b[1;35mrequests.exceptions.ConnectionError\u001b[0m: \u001b[35mHTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000113F59E9810>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, render_template_string, request, redirect, url_for, session, flash\n",
    "import sqlite3\n",
    "from datetime import datetime, timedelta\n",
    "import secrets\n",
    "import hashlib\n",
    "import os\n",
    "from functools import wraps\n",
    "import smtplib\n",
    "from email.mime.text import MIMEText\n",
    "from email.mime.multipart import MIMEMultipart\n",
    "from flask_ngrok import run_with_ngrok\n",
    "\n",
    "# ===================== Flask Setup =====================\n",
    "app = Flask(__name__)\n",
    "app.secret_key = secrets.token_hex(32)\n",
    "app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(hours=24)\n",
    "\n",
    "# Start ngrok for global access\n",
    "run_with_ngrok(app)\n",
    "\n",
    "# ===================== Egyptian National ID =====================\n",
    "government_code = {\n",
    "    '01': 'Cairo', '02': 'Alexandria', '03': 'Port Said', '04': 'Suez',\n",
    "    '11': 'Damietta', '12': 'Dakahlia', '13': 'Ash Sharqia', '14': 'Kaliobeya',\n",
    "    '15': 'Kafr El-Sheikh', '16': 'Gharbia', '17': 'Menoufia', '18': 'Beheira',\n",
    "    '19': 'Ismailia', '21': 'Giza', '22': 'Beni Suef', '23': 'Fayoum',\n",
    "    '24': 'Minya', '25': 'Assiut', '26': 'Sohag', '27': 'Qena',\n",
    "    '28': 'Aswan', '29': 'Luxor', '31': 'Red Sea', '32': 'New Valley',\n",
    "    '33': 'Matrouh', '34': 'North Sinai', '35': 'South Sinai', '88': 'Foreign'\n",
    "}\n",
    "\n",
    "class EgyptNationalID:\n",
    "    def __init__(self, national_id):\n",
    "        self.national_id = national_id\n",
    "        self.birth_date = None\n",
    "        self.government = None\n",
    "        self.gender = None\n",
    "        self.age = None\n",
    "        self.valid = self.validate_national_id()\n",
    "\n",
    "    def validate_national_id(self):\n",
    "        if len(self.national_id) != 14 or not self.national_id.isdigit():\n",
    "            return False\n",
    "        year_prefix = self.national_id[0]\n",
    "        year_number = self.national_id[1:3]\n",
    "        month = self.national_id[3:5]\n",
    "        day = self.national_id[5:7]\n",
    "        government_id = self.national_id[7:9]\n",
    "        rest_of_id = self.national_id[9:13]\n",
    "\n",
    "        if year_prefix == \"2\":\n",
    "            full_year = \"19\" + year_number\n",
    "        elif year_prefix == \"3\":\n",
    "            full_year = \"20\" + year_number\n",
    "        else:\n",
    "            return False\n",
    "\n",
    "        self.gender = \"male\" if int(rest_of_id) % 2 == 1 else \"female\"\n",
    "\n",
    "        try:\n",
    "            self.birth_date = datetime.strptime(f\"{full_year}{month}{day}\", \"%Y%m%d\")\n",
    "            self.birth_date_str = self.birth_date.strftime(\"%Y-%m-%d\")\n",
    "        except ValueError:\n",
    "            return False\n",
    "\n",
    "        self.government = government_code.get(government_id, 'Unknown')\n",
    "\n",
    "        today = datetime.now().date()\n",
    "        birth = self.birth_date.date()\n",
    "        self.age = today.year - birth.year - ((today.month, today.day) < (birth.month, birth.day))\n",
    "\n",
    "        return True\n",
    "\n",
    "# ===================== Email =====================\n",
    "class EmailConfig:\n",
    "    SENDER_EMAIL = os.getenv(\"EMAIL_ADDRESS\", \"your_email@gmail.com\")\n",
    "    SENDER_PASSWORD = os.getenv(\"EMAIL_PASSWORD\", \"your_app_password\")\n",
    "    SMTP_SERVER = \"smtp.gmail.com\"\n",
    "    SMTP_PORT = 587\n",
    "\n",
    "class EmailService:\n",
    "    @staticmethod\n",
    "    def send_verification_code(to_email, code, name):\n",
    "        try:\n",
    "            message = MIMEMultipart('alternative')\n",
    "            message['From'] = EmailConfig.SENDER_EMAIL\n",
    "            message['To'] = to_email\n",
    "            message['Subject'] = f\"Verification Code - {name}\"\n",
    "            html_body = f\"\"\"\n",
    "            <html><body style=\"font-family: Arial; text-align: center; padding: 20px;\">\n",
    "            <div style=\"background: white; max-width: 500px; margin: auto; padding: 40px; border-radius: 15px;\">\n",
    "            <h1>Hello {name}!</h1>\n",
    "            <p>Use this code to verify your account:</p>\n",
    "            <div style=\"background: #667eea; padding: 20px; border-radius: 10px; margin: 20px 0;\">\n",
    "            <p style=\"color: white; font-size: 48px; font-weight: bold; letter-spacing: 8px;\">{code}</p>\n",
    "            </div>\n",
    "            <p style=\"font-size: 14px; color: #555;\">Code valid for 15 minutes</p>\n",
    "            </div></body></html>\n",
    "            \"\"\"\n",
    "            message.attach(MIMEText(html_body, 'html'))\n",
    "            with smtplib.SMTP(EmailConfig.SMTP_SERVER, EmailConfig.SMTP_PORT) as server:\n",
    "                server.starttls()\n",
    "                server.login(EmailConfig.SENDER_EMAIL, EmailConfig.SENDER_PASSWORD)\n",
    "                server.send_message(message)\n",
    "            return True\n",
    "        except Exception as e:\n",
    "            print(f\"Email error: {e}\")\n",
    "            return False\n",
    "\n",
    "# ===================== Database =====================\n",
    "class DatabaseManager:\n",
    "    def __init__(self):\n",
    "        self.conn = sqlite3.connect('fouckn_complete_system.db', check_same_thread=False)\n",
    "        self.conn.execute('PRAGMA journal_mode=WAL;')\n",
    "        self.create_tables()\n",
    "    \n",
    "    def create_tables(self):\n",
    "        c = self.conn.cursor()\n",
    "        # Pending users\n",
    "        c.execute(\"\"\"CREATE TABLE IF NOT EXISTS pending_users (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            national_id TEXT UNIQUE NOT NULL,\n",
    "            birth_date TEXT,\n",
    "            government TEXT,\n",
    "            gender TEXT,\n",
    "            age INTEGER,\n",
    "            first_name TEXT NOT NULL,\n",
    "            last_name TEXT NOT NULL,\n",
    "            email TEXT NOT NULL UNIQUE,\n",
    "            password_hash TEXT NOT NULL,\n",
    "            code_hash TEXT NOT NULL,\n",
    "            created_at TEXT NOT NULL,\n",
    "            expires_at TEXT NOT NULL,\n",
    "            attempts INTEGER DEFAULT 0\n",
    "        )\"\"\")\n",
    "        # Main users\n",
    "        c.execute(\"\"\"CREATE TABLE IF NOT EXISTS users (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            national_id TEXT UNIQUE NOT NULL,\n",
    "            birth_date TEXT,\n",
    "            government TEXT,\n",
    "            gender TEXT,\n",
    "            age INTEGER,\n",
    "            first_name TEXT NOT NULL,\n",
    "            last_name TEXT NOT NULL,\n",
    "            email TEXT NOT NULL UNIQUE,\n",
    "            password_hash TEXT NOT NULL,\n",
    "            verified BOOLEAN DEFAULT 1,\n",
    "            created_at TEXT NOT NULL,\n",
    "            last_login TEXT\n",
    "        )\"\"\")\n",
    "        self.conn.commit()\n",
    "\n",
    "db = DatabaseManager()\n",
    "\n",
    "def get_db():\n",
    "    return db.conn\n",
    "\n",
    "# ===================== Login Required Decorator =====================\n",
    "def login_required(f):\n",
    "    @wraps(f)\n",
    "    def decorated_function(*args, **kwargs):\n",
    "        if 'user_id' not in session:\n",
    "            flash('Please login first', 'warning')\n",
    "            return redirect(url_for('login'))\n",
    "        return f(*args, **kwargs)\n",
    "    return decorated_function\n",
    "\n",
    "# ===================== CSS =====================\n",
    "CSS = \"\"\"<style>\n",
    "* {margin:0; padding:0; box-sizing:border-box;}\n",
    "body {font-family:sans-serif; background: linear-gradient(135deg, #667eea, #764ba2); min-height:100vh; display:flex; justify-content:center; align-items:center; padding:20px;}\n",
    ".container {background:white; border-radius:20px; padding:40px; max-width:500px; width:100%;}\n",
    "h1,h2 {color:#667eea; text-align:center;}\n",
    "input, button {width:100%; padding:12px; margin:10px 0; border-radius:8px; border:1px solid #ccc;}\n",
    "button {background:#667eea; color:white; font-weight:bold; cursor:pointer;}\n",
    ".alert {padding:12px; border-radius:8px; margin-bottom:20px;}\n",
    ".alert-success {background:#d4edda; color:#155724;}\n",
    ".alert-error {background:#f8d7da; color:#721c24;}\n",
    ".alert-warning {background:#fff3cd; color:#856404;}\n",
    "</style>\"\"\"\n",
    "\n",
    "# ===================== Templates =====================\n",
    "REGISTER_TEMPLATE = CSS + \"\"\"\n",
    "<div class=\"container\">\n",
    "<h1>🇪🇬 Egyptian Auth</h1>\n",
    "<h2>📝 Register</h2>\n",
    "{% with messages = get_flashed_messages(with_categories=true) %}\n",
    "{% for category, message in messages %}\n",
    "<div class=\"alert alert-{{ category }}\">{{ message }}</div>\n",
    "{% endfor %}{% endwith %}\n",
    "<form method=\"POST\">\n",
    "<input type=\"text\" name=\"national_id\" placeholder=\"National ID (14 digits)\" required pattern=\"[0-9]{14}\">\n",
    "<input type=\"text\" name=\"first_name\" placeholder=\"First Name\" required>\n",
    "<input type=\"text\" name=\"last_name\" placeholder=\"Last Name\" required>\n",
    "<input type=\"email\" name=\"email\" placeholder=\"Email\" required>\n",
    "<input type=\"password\" name=\"password\" placeholder=\"Password\" required>\n",
    "<button type=\"submit\">📧 Send Verification Code</button>\n",
    "</form>\n",
    "<a href=\"{{ url_for('login') }}\">Already have an account? Login</a>\n",
    "</div>\n",
    "\"\"\"\n",
    "\n",
    "LOGIN_TEMPLATE = CSS + \"\"\"\n",
    "<div class=\"container\">\n",
    "<h1>🇪🇬 Egyptian Auth</h1>\n",
    "<h2>🔐 Login</h2>\n",
    "{% with messages = get_flashed_messages(with_categories=true) %}\n",
    "{% for category, message in messages %}\n",
    "<div class=\"alert alert-{{ category }}\">{{ message }}</div>\n",
    "{% endfor %}{% endwith %}\n",
    "<form method=\"POST\">\n",
    "<input type=\"email\" name=\"email\" placeholder=\"Email\" required>\n",
    "<input type=\"password\" name=\"password\" placeholder=\"Password\" required>\n",
    "<button type=\"submit\">Login</button>\n",
    "</form>\n",
    "<a href=\"{{ url_for('register') }}\">Register here</a>\n",
    "</div>\n",
    "\"\"\"\n",
    "\n",
    "VERIFY_TEMPLATE = CSS + \"\"\"\n",
    "<div class=\"container\">\n",
    "<h1>✅ Verify Account</h1>\n",
    "<p>Check your email: {{ email }}</p>\n",
    "{% with messages = get_flashed_messages(with_categories=true) %}\n",
    "{% for category, message in messages %}\n",
    "<div class=\"alert alert-{{ category }}\">{{ message }}</div>\n",
    "{% endfor %}{% endwith %}\n",
    "<form method=\"POST\">\n",
    "<input type=\"text\" name=\"code\" placeholder=\"6-digit code\" required pattern=\"[0-9]{6}\">\n",
    "<button type=\"submit\">Verify</button>\n",
    "</form>\n",
    "</div>\n",
    "\"\"\"\n",
    "\n",
    "DASHBOARD_TEMPLATE = CSS + \"\"\"\n",
    "<div class=\"container\">\n",
    "<h1>👤 Dashboard</h1>\n",
    "<p>Welcome, {{ user.first_name }} {{ user.last_name }}</p>\n",
    "<p>Email: {{ user.email }}</p>\n",
    "<p>National ID: {{ user.national_id }}</p>\n",
    "<p>Birth Date: {{ user.birth_date }}</p>\n",
    "<p>Government: {{ user.government }}</p>\n",
    "<p>Gender: {{ user.gender }}</p>\n",
    "<p>Age: {{ user.age }}</p>\n",
    "<p>Member Since: {{ user.created_at[:10] }}</p>\n",
    "<p>Last Login: {{ user.last_login[:10] if user.last_login else 'First Login' }}</p>\n",
    "<a href=\"{{ url_for('logout') }}\"><button>Logout</button></a>\n",
    "</div>\n",
    "\"\"\"\n",
    "\n",
    "# ===================== Routes =====================\n",
    "@app.route('/')\n",
    "def index():\n",
    "    if 'user_id' in session:\n",
    "        return redirect(url_for('dashboard'))\n",
    "    return redirect(url_for('login'))\n",
    "\n",
    "# ---------- Register ----------\n",
    "@app.route('/register', methods=['GET','POST'])\n",
    "def register():\n",
    "    if request.method == 'POST':\n",
    "        national_id = request.form['national_id'].strip()\n",
    "        first_name = request.form['first_name'].strip()\n",
    "        last_name = request.form['last_name'].strip()\n",
    "        email = request.form['email'].strip()\n",
    "        password = request.form['password'].strip()\n",
    "\n",
    "        egypt_id = EgyptNationalID(national_id)\n",
    "        if not egypt_id.valid:\n",
    "            flash('Invalid Egyptian National ID', 'error')\n",
    "            return redirect(url_for('register'))\n",
    "\n",
    "        conn = get_db()\n",
    "        if conn.execute(\"SELECT email FROM users WHERE email=?\", (email,)).fetchone():\n",
    "            flash('Email already registered', 'error')\n",
    "            return redirect(url_for('login'))\n",
    "\n",
    "        code = ''.join([str(secrets.randbelow(10)) for _ in range(6)])\n",
    "        password_hash = hashlib.sha256(password.encode()).hexdigest()\n",
    "        code_hash = hashlib.sha256(code.encode()).hexdigest()\n",
    "        created_at = datetime.now().isoformat()\n",
    "        expires_at = (datetime.now() + timedelta(minutes=15)).isoformat()\n",
    "\n",
    "        conn.execute('DELETE FROM pending_users WHERE email=?', (email,))\n",
    "        conn.execute(\"\"\"INSERT INTO pending_users (national_id,birth_date,government,gender,age,first_name,last_name,email,password_hash,code_hash,created_at,expires_at)\n",
    "                        VALUES (?,?,?,?,?,?,?,?,?,?,?,?)\"\"\",\n",
    "                     (national_id, egypt_id.birth_date_str, egypt_id.government, egypt_id.gender, egypt_id.age, first_name, last_name, email, password_hash, code_hash, created_at, expires_at))\n",
    "        conn.commit()\n",
    "\n",
    "        if EmailService.send_verification_code(email, code, first_name):\n",
    "            session['pending_email'] = email\n",
    "            flash('Verification code sent!', 'success')\n",
    "            return redirect(url_for('verify'))\n",
    "        else:\n",
    "            flash('Failed to send email', 'error')\n",
    "            return redirect(url_for('register'))\n",
    "\n",
    "    return render_template_string(REGISTER_TEMPLATE)\n",
    "\n",
    "# ---------- Verify ----------\n",
    "@app.route('/verify', methods=['GET','POST'])\n",
    "def verify():\n",
    "    if 'pending_email' not in session:\n",
    "        flash('Please register first', 'warning')\n",
    "        return redirect(url_for('register'))\n",
    "\n",
    "    email = session['pending_email']\n",
    "    conn = get_db()\n",
    "\n",
    "    if request.method == 'POST':\n",
    "        code = request.form['code'].strip()\n",
    "        code_hash = hashlib.sha256(code.encode()).hexdigest()\n",
    "        row = conn.execute(\"SELECT * FROM pending_users WHERE email=? AND code_hash=?\", (email, code_hash)).fetchone()\n",
    "\n",
    "        if not row:\n",
    "            conn.execute(\"UPDATE pending_users SET attempts=attempts+1 WHERE email=?\", (email,))\n",
    "            conn.commit()\n",
    "            attempts = conn.execute(\"SELECT attempts FROM pending_users WHERE email=?\", (email,)).fetchone()[0]\n",
    "            if attempts >= 3:\n",
    "                conn.execute(\"DELETE FROM pending_users WHERE email=?\", (email,))\n",
    "                conn.commit()\n",
    "                session.pop('pending_email')\n",
    "                flash('Max attempts reached. Register again.', 'error')\n",
    "                return redirect(url_for('register'))\n",
    "            flash(f'Wrong code. Attempts remaining: {3-attempts}', 'error')\n",
    "            return redirect(url_for('verify'))\n",
    "\n",
    "        expires_at = datetime.fromisoformat(row[11])\n",
    "        if datetime.now() > expires_at:\n",
    "            conn.execute(\"DELETE FROM pending_users WHERE email=?\", (email,))\n",
    "            conn.commit()\n",
    "            session.pop('pending_email')\n",
    "            flash('Code expired. Register again.', 'error')\n",
    "            return redirect(url_for('register'))\n",
    "\n",
    "        conn.execute(\"\"\"INSERT INTO users (national_id,birth_date,government,gender,age,first_name,last_name,email,password_hash,created_at)\n",
    "                        VALUES (?,?,?,?,?,?,?,?,?,?)\"\"\",\n",
    "                     (row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9], datetime.now().isoformat()))\n",
    "        conn.execute(\"DELETE FROM pending_users WHERE email=?\", (email,))\n",
    "        conn.commit()\n",
    "        session.pop('pending_email')\n",
    "        flash('Account verified! Welcome!', 'success')\n",
    "        return redirect(url_for('login'))\n",
    "\n",
    "    return render_template_string(VERIFY_TEMPLATE, email=email)\n",
    "\n",
    "# ---------- Login ----------\n",
    "@app.route('/login', methods=['GET','POST'])\n",
    "def login():\n",
    "    if request.method == 'POST':\n",
    "        email = request.form['email'].strip()\n",
    "        password = request.form['password'].strip()\n",
    "        password_hash = hashlib.sha256(password.encode()).hexdigest()\n",
    "\n",
    "        conn = get_db()\n",
    "        row = conn.execute(\"SELECT * FROM users WHERE email=? AND password_hash=?\", (email, password_hash)).fetchone()\n",
    "        if row:\n",
    "            session['user_id'] = row[0]\n",
    "            session['email'] = row[8]\n",
    "            session['first_name'] = row[6]\n",
    "            session['last_name'] = row[7]\n",
    "            session.permanent = True\n",
    "            conn.execute(\"UPDATE users SET last_login=? WHERE id=?\", (datetime.now().isoformat(), row[0]))\n",
    "            conn.commit()\n",
    "            flash('Login successful!', 'success')\n",
    "            return redirect(url_for('dashboard'))\n",
    "        flash('Invalid email/password', 'error')\n",
    "        return redirect(url_for('login'))\n",
    "\n",
    "    return render_template_string(LOGIN_TEMPLATE)\n",
    "\n",
    "# ---------- Dashboard ----------\n",
    "@app.route('/dashboard')\n",
    "@login_required\n",
    "def dashboard():\n",
    "    conn = get_db()\n",
    "    row = conn.execute(\"SELECT * FROM users WHERE id=?\", (session['user_id'],)).fetchone()\n",
    "    user = {\n",
    "        'first_name': row[6],\n",
    "        'last_name': row[7],\n",
    "        'email': row[8],\n",
    "        'national_id': row[1],\n",
    "        'birth_date': row[2],\n",
    "        'government': row[3],\n",
    "        'gender': row[4],\n",
    "        'age': row[5],\n",
    "        'created_at': row[10],\n",
    "        'last_login': row[11]\n",
    "    }\n",
    "    return render_template_string(DASHBOARD_TEMPLATE, user=user)\n",
    "\n",
    "# ---------- Logout ----------\n",
    "@app.route('/logout')\n",
    "def logout():\n",
    "    session.clear()\n",
    "    flash('Logged out successfully', 'success')\n",
    "    return redirect(url_for('login'))\n",
    "\n",
    "# ===================== Run Flask =====================\n",
    "if __name__ == '__main__':\n",
    "    app.run()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9acf8d00-0b66-4664-b2c4-0b522e69dbec",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
